const express = require('express');
const globalConfig = require('./config')
const loader = require('./loader')

const app = express()

app.use(express.static('./page/'))
app.post('/editEveryDay', loader.get('/editEveryDay'))
app.get('/queryEveryDay', loader.get('/queryEveryDay'))
app.post('/editBlog', loader.get('/editBlog'))
app.get('/queryBlogByPage', loader.get('/queryBlogByPage'))
app.get('/queryBlogCount', loader.get('/queryBlogCount'))
app.get('/queryBlogById', loader.get('/queryBlogById'))
app.get('/addComment', loader.get('/addComment'))
app.get('/queryRandomCode', loader.get('/queryRandomCode'))
app.get('/queryCommentByBlogId', loader.get('/queryCommentByBlogId'))
app.get('/queryCountByBlogId', loader.get('/queryCountByBlogId'))
app.get('/queryAllBlog', loader.get('/queryAllBlog'))
app.get('/queryRandomTags', loader.get('/queryRandomTags'))
app.get('/queryHotBlog', loader.get('/queryHotBlog'))
app.get('/queryNewComment', loader.get('/queryNewComment'))
app.get('/queryBlogByTag', loader.get('/queryBlogByTag'))
app.get('/queryCountByTag', loader.get('/queryCountByTag'))
app.listen(globalConfig.port, function () {
    console.log('请访问： 127.0.0.1:10086')
})
